name: API Gateway Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * *'

jobs:
  smoke:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-http-smoke.yml@ed2f7d29467bf1fd6ec40df3953b3ee128ba3f04
    with:
      paths: |-
        /
        /index.html
    secrets:
      SMOKE_BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
