name: Build All (Go Matrix)

on:
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'
  push:
    branches: [main, master]
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  build:
    uses: FelipeFuhr/ffreis-workflows-go/.github/workflows/go-cross-build-matrix.yml@main
    with:
      go-version: "1.25.8"
      working-directory: "."
      targets: |-
        ./cmd/build-static
        ./cmd/web
