name: DeepSource

on:
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'
  push:
    branches: [main, master]
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  deepsource:
    uses: FelipeFuhr/ffreis-workflows-go/.github/workflows/go-deepsource-coverage.yml@main
    with:
      go-version: "1.25.8"
      working-directory: "."
    secrets:
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
