name: Lefthook

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lefthook:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-lefthook.yml@ed2f7d29467bf1fd6ec40df3953b3ee128ba3f04
    with:
      working-directory: "."
      go-version: "1.25.8"
      lefthook-bootstrap-command: "make lefthook-bootstrap"
      lefthook-bin: ".bin/lefthook"
